CREATE DATABASE eTouristAgencyDB
GO
USE eTouristAgencyDB
GO
CREATE TABLE City (Id uniqueidentifier NOT NULL, Name nvarchar(100) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NULL, ModifiedBy uniqueidentifier NULL, CountryId uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Country (Id uniqueidentifier NOT NULL, Name nvarchar(255) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NULL, ModifiedBy uniqueidentifier NULL, PRIMARY KEY (Id));
CREATE TABLE EmailVerification (Id uniqueidentifier NOT NULL, VerificationKey varchar(20) NOT NULL, UserId uniqueidentifier NOT NULL, ValidFrom datetime2(7) NOT NULL, ValidTo datetime2(7) NOT NULL, EmailVerificationTypeId uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE EntityCode (Id uniqueidentifier NOT NULL, Name nvarchar(255) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE EntityCodeValue (Id uniqueidentifier NOT NULL, Name nvarchar(255) NOT NULL, EntityCodeId uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NULL, ModifiedBy uniqueidentifier NULL, PRIMARY KEY (Id));
CREATE TABLE Hotel (Id uniqueidentifier NOT NULL, Name nvarchar(255) NOT NULL, CityId uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, StarRating int NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE HotelImage (Id uniqueidentifier NOT NULL, ImageBytes varbinary(max) NOT NULL, HotelId uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Offer (Id uniqueidentifier NOT NULL, TripStartDate datetime2(7) NOT NULL, NumberOfNights int NOT NULL, TripEndDate datetime2(7) NOT NULL, Carriers nvarchar(255) NOT NULL, Description nvarchar(max) NOT NULL, FirstPaymentDeadline datetime2(7) NOT NULL, LastPaymentDeadline datetime2(7) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, OfferNo bigint NOT NULL UNIQUE, DeparturePlace nvarchar(255) NOT NULL, HotelId uniqueidentifier NOT NULL, OfferStatusId uniqueidentifier NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE OfferDiscount (Id uniqueidentifier NOT NULL, DiscountTypeId uniqueidentifier NOT NULL, Discount decimal(15, 2) NOT NULL, OfferId uniqueidentifier NOT NULL, ValidFrom datetime2(7) NOT NULL, ValidTo datetime2(7) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE OfferDocument (Id uniqueidentifier NOT NULL, DocumentBytes varbinary(max) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE OfferImage (Id uniqueidentifier NOT NULL, ImageBytes varbinary(max) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Reservation (Id uniqueidentifier NOT NULL, UserId uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, PaidAmount decimal(15, 2) NOT NULL, CancellationDate datetime2(7) NOT NULL, ReservationNo bigint NOT NULL UNIQUE, TotalCost decimal(10, 2) NOT NULL, PassengersJson nvarchar(max) NOT NULL, OfferDiscountId uniqueidentifier NOT NULL, ReservationStatusId uniqueidentifier NOT NULL, RoomOfferId uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, CreatedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE ReservationPayment (Id uniqueidentifier NOT NULL, DocumentBytes varbinary(max) NOT NULL, ReservationId uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE ReservationReview (Id uniqueidentifier NOT NULL, AccommodationRating int NOT NULL, ServiceRating int NOT NULL, Description nvarchar(max) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Role (Id uniqueidentifier NOT NULL, Name varchar(50) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Room (Id uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, RoomTypeId uniqueidentifier NOT NULL, OfferId uniqueidentifier NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE RoomOffer (Id uniqueidentifier NOT NULL, BoardTypeId uniqueidentifier NOT NULL, PricePerPerson decimal(15, 2) NOT NULL, ChildDiscount decimal(15, 2) NOT NULL, OfferRoomId uniqueidentifier NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NOT NULL, ModifiedBy uniqueidentifier NOT NULL, PRIMARY KEY (Id));
CREATE TABLE RoomType (Id uniqueidentifier NOT NULL, RoomCapacity int NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, CreatedBy uniqueidentifier NULL, ModifiedBy uniqueidentifier NULL, PRIMARY KEY (Id));
CREATE TABLE [User] (Id uniqueidentifier NOT NULL, Username varchar(100) NOT NULL UNIQUE, PasswordHash varchar(max) NOT NULL, FirstName nvarchar(100) NOT NULL, LastName nvarchar(100) NOT NULL, Email varchar(255) NOT NULL UNIQUE, PhoneNumber varchar(50) NOT NULL, CreatedOn datetime2(7) DEFAULT GETDATE() NOT NULL, ModifiedOn datetime2(7) DEFAULT GETDATE() NOT NULL, IsActive bit NOT NULL, IsVerified bit NOT NULL, PRIMARY KEY (Id));
CREATE TABLE UserRole (UserId uniqueidentifier NOT NULL, RoleId uniqueidentifier NOT NULL, PRIMARY KEY (UserId, RoleId));
ALTER TABLE UserRole ADD CONSTRAINT FKUserRole407378 FOREIGN KEY (UserId) REFERENCES [User] (Id);
ALTER TABLE UserRole ADD CONSTRAINT FKUserRole885973 FOREIGN KEY (RoleId) REFERENCES Role (Id);
ALTER TABLE Reservation ADD CONSTRAINT FKReservatio730164 FOREIGN KEY (UserId) REFERENCES [User] (Id);
ALTER TABLE Room ADD CONSTRAINT FKRoom493867 FOREIGN KEY (OfferId) REFERENCES Offer (Id);
ALTER TABLE ReservationPayment ADD CONSTRAINT FKReservatio264129 FOREIGN KEY (ReservationId) REFERENCES Reservation (Id);
ALTER TABLE Hotel ADD CONSTRAINT FKHotel717322 FOREIGN KEY (CityId) REFERENCES City (Id);
ALTER TABLE Offer ADD CONSTRAINT FKOffer118351 FOREIGN KEY (HotelId) REFERENCES Hotel (Id);
ALTER TABLE HotelImage ADD CONSTRAINT FKHotelImage536976 FOREIGN KEY (HotelId) REFERENCES Hotel (Id);
ALTER TABLE OfferDiscount ADD CONSTRAINT FKOfferDisco517182 FOREIGN KEY (OfferId) REFERENCES Offer (Id);
ALTER TABLE Reservation ADD CONSTRAINT FKReservatio911731 FOREIGN KEY (OfferDiscountId) REFERENCES OfferDiscount (Id);
ALTER TABLE EntityCodeValue ADD CONSTRAINT FKEntityCode668051 FOREIGN KEY (EntityCodeId) REFERENCES EntityCode (Id);
ALTER TABLE Offer ADD CONSTRAINT FKOffer728835 FOREIGN KEY (OfferStatusId) REFERENCES EntityCodeValue (Id);
ALTER TABLE Room ADD CONSTRAINT FKRoom188940 FOREIGN KEY (RoomTypeId) REFERENCES RoomType (Id);
ALTER TABLE Reservation ADD CONSTRAINT FKReservatio127771 FOREIGN KEY (ReservationStatusId) REFERENCES EntityCodeValue (Id);
ALTER TABLE ReservationReview ADD CONSTRAINT FKReservatio885176 FOREIGN KEY (Id) REFERENCES Reservation (Id);
ALTER TABLE EmailVerification ADD CONSTRAINT FKEmailVerif613795 FOREIGN KEY (UserId) REFERENCES [User] (Id);
ALTER TABLE EmailVerification ADD CONSTRAINT FKEmailVerif701141 FOREIGN KEY (EmailVerificationTypeId) REFERENCES EntityCodeValue (Id);
ALTER TABLE OfferImage ADD CONSTRAINT FKOfferImage255475 FOREIGN KEY (Id) REFERENCES Offer (Id);
ALTER TABLE OfferDocument ADD CONSTRAINT FKOfferDocum817671 FOREIGN KEY (Id) REFERENCES Offer (Id);
ALTER TABLE Reservation ADD CONSTRAINT FKReservatio505422 FOREIGN KEY (RoomOfferId) REFERENCES RoomOffer (Id);
ALTER TABLE RoomOffer ADD CONSTRAINT FKRoomOffer670665 FOREIGN KEY (OfferRoomId) REFERENCES Room (Id);
ALTER TABLE Offer ADD CONSTRAINT FKOffer882796 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE Offer ADD CONSTRAINT FKOffer644415 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE Room ADD CONSTRAINT FKRoom427895 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE Room ADD CONSTRAINT FKRoom189514 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE RoomType ADD CONSTRAINT FKRoomType639052 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE RoomType ADD CONSTRAINT FKRoomType400671 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE RoomOffer ADD CONSTRAINT FKRoomOffer602746 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE RoomOffer ADD CONSTRAINT FKRoomOffer364365 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE Reservation ADD CONSTRAINT FKReservatio955634 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE Reservation ADD CONSTRAINT FKReservatio194016 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE OfferImage ADD CONSTRAINT FKOfferImage632224 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE OfferImage ADD CONSTRAINT FKOfferImage870605 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE OfferDocument ADD CONSTRAINT FKOfferDocum70028 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE OfferDocument ADD CONSTRAINT FKOfferDocum308409 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE Hotel ADD CONSTRAINT FKHotel65883 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE Hotel ADD CONSTRAINT FKHotel827501 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE City ADD CONSTRAINT FKCity880359 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE City ADD CONSTRAINT FKCity641978 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE City ADD CONSTRAINT FKCity241283 FOREIGN KEY (CountryId) REFERENCES Country (Id);
ALTER TABLE Country ADD CONSTRAINT FKCountry505983 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE Country ADD CONSTRAINT FKCountry744364 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE EntityCodeValue ADD CONSTRAINT FKEntityCode596278 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE EntityCodeValue ADD CONSTRAINT FKEntityCode834659 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE HotelImage ADD CONSTRAINT FKHotelImage772530 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE HotelImage ADD CONSTRAINT FKHotelImage10912 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE OfferDiscount ADD CONSTRAINT FKOfferDisco532645 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE OfferDiscount ADD CONSTRAINT FKOfferDisco771026 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE ReservationReview ADD CONSTRAINT FKReservatio887494 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE ReservationReview ADD CONSTRAINT FKReservatio350886 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
ALTER TABLE ReservationPayment ADD CONSTRAINT FKReservatio536480 FOREIGN KEY (CreatedBy) REFERENCES [User] (Id);
ALTER TABLE ReservationPayment ADD CONSTRAINT FKReservatio196729 FOREIGN KEY (ModifiedBy) REFERENCES [User] (Id);
