version: '3.8'

services:
 etouristagency-sql:
  image: mcr.microsoft.com/mssql/server:2019-latest
  restart: unless-stopped
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Admin123!@#
    - MSSQL_PID=Developer
  ports:
    - "1434:1433"
  expose:
    - "1433"
  networks:
    - etouristnet

 etouristagency-rabbitmq:
   image: rabbitmq:3-management
   restart: unless-stopped
   environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
   ports:
     - "5672:5672"
     - "15672:15672"
   networks:
     - etouristnet
   healthcheck:
     test: rabbitmq-diagnostics -q ping
     interval: 30s
     timeout: 30s
     retries: 3

 etouristagency-api:
  build:
    context: .
  container_name: etouristagency-api
  restart: unless-stopped
  ports:
    - "5000:5000"
    - "5001:5001"
  environment:
    - ASPNETCORE_URLS=https://+:5000;http://+:5001
    - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
  networks:
    - etouristnet
  depends_on:
    - etouristagency-sql
    - etouristagency-rabbitmq

 etouristagency-notifications:
   build:
     context: .
   container_name: etouristagency-notifications
   restart: unless-stopped
   entrypoint: ["dotnet", "Notifications/eTouristAgencyAPI.Notifications.dll"]
   networks:
     - etouristnet
   depends_on:
     etouristagency-api:
       condition: service_started
     etouristagency-rabbitmq:
       condition: service_healthy

networks:
 etouristnet:
   driver: bridge